[package]
name = "fruit-id"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15"
tokio-tungstenite = { version = "0.24", default-features = false, features = ["rustls-tls-webpki-roots", "connect"] }
futures-util = "0.3"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
actix-web = "4.14.1"
actix-cors = "0.7.1"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
